version: '3'
services:
  mean:
    image: meanjs/mean
    ports:
     - "3000:3000"
     - "5858:5858"
     - "8080:8080"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - DB_1_PORT_27017_TCP_ADDR=172.31.23.95
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
     - frontend

networks:
  frontend:
    driver: overlay
